// <auto-generated />
namespace StudentProjectManagementAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitDbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201704091049046_InitDbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
